framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'print@fheuschen.de'
        headers:
            from: 'Heinrich-von-Gagern-Gymnasium <print@fheuschen.de>'
